### ISSUE TITLE
Keyword .model of LPN file is not accepted

### ISSUE THREAD

**Issue by danilovesky** [MyersResearchGroup/ATACS#60]
The LPN parser does accept the model name declaration, which is preceded by the `.model' keyword.
For example, parsing of the following input results in a syntax error at line 1:
```
.model inverter
.inputs in
.outputs out
#@.init_state [01]
.graph
p0 in+
in+ out-
out- in-
in- out+
out+ p0
.marking {p0}
.end
```

**Comment by cjmyers** [comment]
It uses .name

I’m not aware of .model.  This was not part of the .g format when we originally wrote this parser.

Chris

**Comment by danilovesky** [comment]
Great! I will use `.name` instead of `.model` then - problem solved :)
